import { generatePeerId, cn } from "@/lib/utils";
import { validatePeerId } from "@/lib/peer";

describe("generatePeerId", () => {
  it("should generate a string of 8-10 characters", () => {
    for (let i = 0; i < 50; i++) {
      const id = generatePeerId();
      expect(id.length).toBeGreaterThanOrEqual(8);
      expect(id.length).toBeLessThanOrEqual(10);
    }
  });

  it("should only contain alphanumeric characters", () => {
    for (let i = 0; i < 50; i++) {
      const id = generatePeerId();
      expect(id).toMatch(/^[a-zA-Z0-9]+$/);
    }
  });

  it("should generate unique IDs", () => {
    const ids = new Set<string>();
    for (let i = 0; i < 100; i++) {
      ids.add(generatePeerId());
    }
    // With 62^8 possible combinations, collisions should be extremely unlikely
    expect(ids.size).toBeGreaterThan(95);
  });
});

describe("validatePeerId", () => {
  it("should accept valid alphanumeric IDs", () => {
    expect(validatePeerId("abc12345")).toBe(true);
    expect(validatePeerId("AbCdEf12")).toBe(true);
    expect(validatePeerId("testID")).toBe(true);
    expect(validatePeerId("ABCDEFGHIJ")).toBe(true);
  });

  it("should reject empty strings", () => {
    expect(validatePeerId("")).toBe(false);
  });

  it("should reject IDs shorter than 3 characters", () => {
    expect(validatePeerId("ab")).toBe(false);
    expect(validatePeerId("a")).toBe(false);
  });

  it("should reject IDs with special characters", () => {
    expect(validatePeerId("abc-123")).toBe(false);
    expect(validatePeerId("abc_123")).toBe(false);
    expect(validatePeerId("abc 123")).toBe(false);
    expect(validatePeerId("abc!@#")).toBe(false);
  });

  it("should accept IDs generated by generatePeerId", () => {
    for (let i = 0; i < 50; i++) {
      const id = generatePeerId();
      expect(validatePeerId(id)).toBe(true);
    }
  });
});

describe("cn utility", () => {
  it("should merge class names", () => {
    const result = cn("foo", "bar");
    expect(result).toBe("foo bar");
  });

  it("should handle conditional classes", () => {
    const result = cn("foo", false && "bar", "baz");
    expect(result).toBe("foo baz");
  });

  it("should handle undefined values", () => {
    const result = cn("foo", undefined, "bar");
    expect(result).toBe("foo bar");
  });

  it("should merge Tailwind classes correctly", () => {
    const result = cn("px-2", "px-4");
    expect(result).toBe("px-4");
  });
});
